### ISSUE TITLE
REFLECTIONS: Revisit Project Design

### ISSUE THREAD

**Issue by hoaikhanhnguyen** [hoaikhanhnguyen/CS4B_Project#17]
Revisit and discuss any changes that need to be made to the current design.

**One discussion one is the menu button on the game board. Is this required?** Current design does not close out the scenes, so the menu remains open, but this allows the player to start multiple games.

Do we need all the current buttons or do we need to add any?

**Comment by jhynh** [comment]
The menu button on the gameboard was part of the draft, but I don't believe it to be needed. The pause button is more than enough.

**Comment by hoaikhanhnguyen** [comment]
We decided to remove the menu button for now. Please post any reflections you may have as a comment.
