### ISSUE TITLE
Optimize AI Moves for 1 Player Game

### ISSUE THREAD

**Issue by hoaikhanhnguyen** [hoaikhanhnguyen/CS4B_Project#27]
use Min/Max algorithm to create an optimized ai opponent

**Comment by jhynh** [comment]
This portion has two parts, refactoring the algorithm for the javaFX api and the implementation of the algorithm itself. Perhaps using an existing minimax algorithm (instead of making our own; at least as a proof of "deliverability")  will ease our development process.

**Comment by hoaikhanhnguyen** [comment]
pull request pending on branch min-max-algo
